### ISSUE TITLE
ComputerCraft error

### ISSUE THREAD

**Issue by wsanders99** [Forte40/openbee#9]
I am getting openbee:642: Other inventory not found.

It's looking for the Analyzer and the direction is set to up since its on top, but even if I move it on the right and change it to west it still give me the same error.

**Comment by Deweyoxberg** [comment]
Other Inventory refers to the product and ditch chests. Make sure you have a chest directly below the apiary. A double wide wooden chest on top of the apiary can serve as your ditch chest.
